version: "3.8"

services:
  activemq:
    image: apache/activemq-classic:6.1.2
    container_name: activemq
    ports:
      - "61616:61616" # JMS
      - "8161:8161" # Web console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
